feat!: add new rules/configs/plugins
ChainSafe/eslint-config pull request #20
Opened 2024-01-09 12:07 UTC by sztok7

2024-01-09 12:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/eslint-config?pullRequest=20) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/eslint-config?pullRequest=20) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/eslint-config?pullRequest=20) it.</sub>

2024-01-10 09:14 UTC, sztok7 commented on index.js
> +        "@typescript-eslint/consistent-type-definitions": ["error", "type"],
I think it's a good practice to use either types or interfaces (personally prefer types, but this rule can be changed or turned off if preferences differ or if the  project is a dependency of another that relies on a specific type definition style)

2024-01-10 09:14 UTC, sztok7 commented on index.js
> -        "import/order": [
removed this, since it'll be handled by `simple-import-sort` :)

2024-01-10 09:18 UTC, sztok7 commented on test/validate.spec.js
most changes are just code style + added some new eslint error assertions

2024-01-10 09:47 UTC, sztok7 commented on test/validate.spec.js
most changes are just code style + some new rule error assertions

2024-01-10 11:42 UTC, mpetrunic requested changes

2024-01-10 11:42 UTC, mpetrunic commented on index.js
> +        "airbnb-base",
Let's not put this under base rule. You should make new file "react.js" that extends from index.js and adds react specific rules.

2024-01-23 18:41 UTC, closed without merging