feat: add vite config; update yarn;
ChainSafe/eslint-config pull request #8
Opened 2023-04-06 14:47 UTC by Lykhoyda

2023-04-11 08:44 UTC, BeroBurny commented on tsconfig.json
what is the rationale for adding `jsx`, `isolatedModules`, `types`, and `useDefineForClassFields`?

2023-04-11 09:07 UTC, Lykhoyda commented on tsconfig.json
You can find all the info about typescript configuration with vite here https://vitejs.dev/guide/features.html#typescript-compiler-options

The "jsx" option is debatable, as react js is the most commonly used framework it probably makes sense to have preconfigured it by default. But we can keep it with default value as well

2023-04-11 10:26 UTC, BeroBurny commented on tsconfig.json
I meant rationale for this project, as there is no usage of vite, jsx, transpiring ts to js

2023-07-03 12:24 UTC, mpetrunic commented
added easier testing in #11

2023-07-03 12:59 UTC, mpetrunic requested changes
Please just add vite eslint rules, no need to modify projects tsconfig^^

2023-08-17 10:35 UTC, closed without merging